import fs from "fs-extra";
import path from "path";

export async function scaffoldProject(ctx: any, answers: Record<string, any>) {
	const projectName = answers.projectName || ctx.cliName || "appinit-app";
	const targetDir = path.resolve(ctx.cwd, projectName);

	if (await fs.pathExists(targetDir)) {
		throw new Error(`Target directory already exists: ${targetDir}`);
	}

	await fs.ensureDir(targetDir);

	// Minimal package.json
	const pkg = {
		name: projectName,
		version: "0.1.0",
		description: answers.description ?? "",
		author: answers.author ?? "",
		scripts: {
			dev: "node -e \"console.log('no dev script configured')\"",
		},
	};

	await fs.writeJSON(path.join(targetDir, "package.json"), pkg, { spaces: 2 });
	await fs.writeFile(
		path.join(targetDir, "README.md"),
		`# ${projectName}\n\nGenerated by Appinit CLI.\n`,
	);

	// create src folder if requested by structure
	if (answers.structure !== "flat") {
		await fs.ensureDir(path.join(targetDir, "src"));
		await fs.writeFile(path.join(targetDir, "src", "index.js"), "// entry\n");
	}

	console.log(`📁 Created project at ${targetDir}`);
}
