import type { Answers } from "./answers.js";
export declare const isFrontend: (a: Answers) => boolean;
export declare const isBackend: (a: Answers) => boolean;
export declare const isStaticFrontend: (a: Answers) => boolean;
export declare const isServerlessBackend: (a: Answers) => boolean;
export * from "./common.js";
export * from "./frontend.js";
export * from "./backend.js";
export * from "./auth.js";
export * from "./deploy.js";
export * from "./answers.js";
export * from "./engine";
export * from "./git";
export * from "./install.js";
export * from "./template.js";
export * from "./template/file.js";
export * from "./plugin.js";
export * from "./registry.js";
export * from "./marketplace.js";
export * from "./project.js";
export * from "./workspace.js";
export * from "./validation.js";
export * from "./errors.js";
export * from "./events.js";
export * from "./infer.js";
